NantiSchool/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'NantiSchool.views.home', name='home'),

    url(r'^register/', 'UsersExtended.views.register', name='register'),
    url(r'^login/', 'UsersExtended.views.login_custom', name='login'),
    url(r'^logout/', 'UsersExtended.views.logout_custom', name='logout'),
    url(r'^adduser/', 'UsersExtended.views.adduser', name='adduser'),
    url(r'^edituser/(\d+)', 'UsersExtended.views.edituser', name='edituser'),
    url(r'^edituser/', 'UsersExtended.views.listusers', name='listusers'),
    url(r'^updateuser/', 'UsersExtended.views.updateuser', name='updateuser'),
    url(r'^deluser/(\d+)', 'UsersExtended.views.deluser', name='deluser'),
    #url(r'^NantiSchool/', include('NantiSchool.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^Exams/$', 'Exams.views.list', name='list_exams'),
    url(r'^Exams/Take/(?P<exam_id>\d+)/$', 'Exams.views.take', name='take_exams'),
    url(r'^Exams/AnswerQuestion/', 'Exams.views.answer'),

    #CRUD
    url(r'^Exams/Create', 'Exams.views.create', name='create_exams'),
    url(r'^Exams/Edit/(?P<exam_id>\d+)/$', 'Exams.views.edit', name='edit_exams'),
    url(r'^Exams/Delete/(?P<exam_id>\d+)/$', 'Exams.views.delete', name="delete_exams"),
    url(r'^Exams/EditExamData/', 'Exams.views.edit_exam_data'),

    #Question CRUD
    url(r'^Exams/AddQuestion/', 'Exams.views.add_question'),
    url(r'^Exams/EditQuestion/', 'Exams.views.edit_question'),
    url(r'^Exams/DeleteQuestion/', 'Exams.views.delete_question'),

    #Option CRUD
    url(r'^Exams/AddOption/', 'Exams.views.add_option'),
    url(r'^Exams/EditOption/', 'Exams.views.edit_option'),
    url(r'^Exams/DeleteOption/', 'Exams.views.delete_option'),
    url(r'^Exams/EditCheckbox/', 'Exams.views.edit_checkbox'),

    url(r'^admin/', include(admin.site.urls)),
)

UsersExtended/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):

	is_teacher = models.BooleanField(default=False)
	exams_completed = models.IntegerField(default=0)

	user = models.ForeignKey(User)

	def __unicode__(self):
		return "UserProfile for: " + self.user.username

NantiSchool/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from UsersExtended.models import UserProfile

@login_required
def home(request):
	return redirect('list_exams')

NantiSchool/templates/NantiSchool/home.html
{% extends 'base.html' %}

{% block style %}
{% endblock %}

{% block base_content %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url list_exams %}">NantiSchool</a>
          <div class="nav-collapse collapse">
            <p style="margin-left: 20px; color: white !important; text-decoration: none;" class="navbar-text pull-right"><a style="color: white;" href="{% url logout %}">Útskrá</a></p>
            <p class="navbar-text pull-right">
              Innskráður sem <a href="#" class="navbar-link">{{ request.user.username }}</a>
            </p>

            <ul class="nav">
              <li><h5 id="savingMessage" style="color: white; font-weight: bold;"></h5></li>
              <li ><img id="titleLoader" style="margin-left: 15px; display: none; height: 40px important!; margin-top: 10px;"  src="/static/img/loader.gif" /></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Aðalvalmynd</li>
              <li class="{% block exams %}{% endblock %}"><a href="{% url list_exams %}">Próf</a></li>
              {% if request.user.userprofile_set.get.is_teacher %}
              <li class="nav-header">Kennaratól</li>
              <li class="{% block create_exam %}{% endblock %}"><a href="{% url create_exams %}">Bæta við prófi</a></li>
                  <li><a href="#"><span data-target="#notendaumsjon" data-toggle="collapse">Notendaumsjón <i class="icon-chevron-down"></i></span></a></li>
                  <ul class="nav nav-list collapse" id="notendaumsjon">
                      <li><a href="/adduser">Bæta við notanda</a></li>
                      <li><a href="/edituser">Breyta notendum</a></li>
                  </ul>
              {% endif %}
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">

          {% block content %}
          {% endblock %}

        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 1337 d351gn3r5 2013</p>
      </footer>

    </div><!--/.fluid-container-->

{% endblock %}

NantiSchool/templates/NantiSchool/overview.html
{% extends 'NantiSchool/home.html' %}

{% block main %}active{% endblock %}

{% block content %}


{% endblock %}