NantiSchool/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'NantiSchool.views.home', name='home'),

    url(r'^register/', 'UsersExtended.views.register', name='register'),
    url(r'^login/', 'UsersExtended.views.login_custom', name='login'),
    url(r'^logout/', 'UsersExtended.views.logout_custom', name='logout'),
    url(r'^adduser/', 'UsersExtended.views.adduser', name='adduser'),
    url(r'^edituser/(\d+)', 'UsersExtended.views.edituser', name='edituser'),
    url(r'^edituser/', 'UsersExtended.views.listusers', name='listusers'),
    url(r'^updateuser/', 'UsersExtended.views.updateuser', name='updateuser'),
    url(r'^deluser/(\d+)', 'UsersExtended.views.deluser', name='deluser'),
    #url(r'^NantiSchool/', include('NantiSchool.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^Exams/$', 'Exams.views.list', name='list_exams'),
    url(r'^Exams/Take/(?P<exam_id>\d+)/$', 'Exams.views.take', name='take_exams'),
    url(r'^Exams/AnswerQuestion/', 'Exams.views.answer'),

    #CRUD
    url(r'^Exams/Create', 'Exams.views.create', name='create_exams'),
    url(r'^Exams/Edit/(?P<exam_id>\d+)/$', 'Exams.views.edit', name='edit_exams'),
    url(r'^Exams/Delete/(?P<exam_id>\d+)/$', 'Exams.views.delete', name="delete_exams"),
    url(r'^Exams/EditExamData/', 'Exams.views.edit_exam_data'),

    #Question CRUD
    url(r'^Exams/AddQuestion/', 'Exams.views.add_question'),
    url(r'^Exams/EditQuestion/', 'Exams.views.edit_question'),
    url(r'^Exams/DeleteQuestion/', 'Exams.views.delete_question'),

    #Option CRUD
    url(r'^Exams/AddOption/', 'Exams.views.add_option'),
    url(r'^Exams/EditOption/', 'Exams.views.edit_option'),
    url(r'^Exams/DeleteOption/', 'Exams.views.delete_option'),
    url(r'^Exams/EditCheckbox/', 'Exams.views.edit_checkbox'),

    url(r'^admin/', include(admin.site.urls)),
)

Exams/models.py
from django.db import models
from django.contrib.auth.models import User

class Exam(models.Model):

	name = models.TextField()
	course = models.TextField()

	creation_date = models.DateField(auto_now_add=True)
	due_date_time = models.DateField(null=False)

	video = models.URLField(max_length=1000, null=True)

	value = models.IntegerField(default=0)
	created_by = models.ForeignKey(User)

class Question(models.Model):

	question = models.TextField(null=False)
	exam = models.ForeignKey(Exam)


class Option(models.Model):

	option = models.TextField(null=False)
	correct = models.BooleanField(default=False)
	question = models.ForeignKey(Question)


class StudentTakesExam(models.Model):
	
	student = models.ForeignKey(User)
	exam = models.ForeignKey(Exam)
	started = models.DateField(auto_now_add=True)
	finished = models.DateField(default=None, null=True)

class StudentAnswersQuestion(models.Model):

	takes_exam = models.ForeignKey(StudentTakesExam)
	option = models.ForeignKey(Option)
	question = models.ForeignKey(Question)

UsersExtended/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):

	is_teacher = models.BooleanField(default=False)
	exams_completed = models.IntegerField(default=0)

	user = models.ForeignKey(User)

	def __unicode__(self):
		return "UserProfile for: " + self.user.username

Exams/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, Http404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from Exams.models import *
import datetime
import simplejson as json

@login_required
def create(request):
	if request.method == "GET":
		#Create default exam.
		exam = Exam(name="'Unnamed exam'",
					course="No course specified",
					created_by=request.user,
					due_date_time=datetime.date.today() + datetime.timedelta(days=7))
		exam.save()
		#Formatting the time according to the html5 date input standard.
		#browser decides how to display the string in the input element.
		exam.creation_date = exam.creation_date.strftime("%Y-%m-%d") 
		exam.due_date_time = exam.due_date_time.strftime("%Y-%m-%d")
		return render(request, 'Exams/create.html', {'exam' : exam })
	else:
		raise Http404

@login_required
def take(request, exam_id):
	if request.method == "GET":
		exam = Exam.objects.get(id=exam_id)
		mtm = StudentTakesExam.objects.get_or_create(exam=exam, student=request.user)
		if mtm[0].finished:
			return render(request, 'Exams/take.html', {'finished' : True })
		elif exam.due_date_time < datetime.date.today():
			return render(request, 'Exams/take.html', {'expired' : True })
		else:
			return render(request, 'Exams/take.html', {'exam' : exam, 'takes_exam' : mtm[0] })

	else:#if POST
		exam = Exam.objects.get(id=exam_id)
		mtm = StudentTakesExam.objects.get(student=request.user, exam=exam)
		mtm.finished = datetime.date.today()
		mtm.save()
		return redirect(list)


@login_required
def edit(request, exam_id):
	if request.method == "GET":
		#make sure user is a teacher.
		if request.user.userprofile_set.get().is_teacher:
			exam = Exam.objects.get(id=exam_id)
			exam.creation_date = exam.creation_date.strftime("%Y-%m-%d") 
			exam.due_date_time = exam.due_date_time.strftime("%Y-%m-%d")
			questions = None
			try:
				questions = Question.objects.filter(exam=exam)
			except Exception, e:
				print e
				#If the exam doesn't have any questions then questions is set to None
				pass
			return render(request, 'Exams/edit.html', {'exam' :  exam, 'questions' : questions })
	else:
		#No POST method, or student trying to edit exam.
		raise Http404

@login_required
def delete(request, exam_id):
	if request.method == "GET":
		#make sure user is a teacher.
		if request.user.userprofile_set.get().is_teacher:
			exam = Exam.objects.get(id=exam_id)
			#Django makes sure all the related objects (questions, options) get deleted as well.
			exam.delete()
			return redirect(list)

@login_required
def list(request):
	#Fetch all exams and order them from newest first.
	exam_list = Exam.objects.all().order_by('due_date_time')
	for e in exam_list:
		try:
			correct_count = 0

			#Calculate the score of the student for each exam.
			taken = StudentTakesExam.objects.get(student=request.user, exam=e)
			if taken.finished is None:
				e.grade = None
			else:
				questions_answered = taken.studentanswersquestion_set.all()
				for answer in questions_answered:
					if answer.option.correct:
						correct_count += 1
				e.correct = correct_count
				e.grade = float(correct_count) / e.question_set.all().count() * 10

			# Get every student that has taken the exam and calculate his score
			students_taken_exam = e.studenttakesexam_set.filter(exam=e).exclude(finished=None)
			grade_list = []
			for taken_exam in students_taken_exam:
				correct_count = 0
				taken = StudentTakesExam.objects.get(student=taken_exam.student, exam=e)
				questions_answered = taken.studentanswersquestion_set.all()
				for answer in questions_answered:
					if answer.option.correct:
						correct_count += 1
				grade = float(correct_count) / e.question_set.all().count() * 10
				grade_list.append(grade)
			grade_list.sort()
			grade_list.reverse()
			# Find the position the users grade is in the score list
			e.position = grade_list.index(e.grade) + 1
			e.exam_count = len(grade_list)
			e.taken = taken.finished
			# if taken.finished:
			# 	e.taken = True
			# else:
			# 	e.taken = False
		except Exception, ex:
			print ex
			e.taken = False
			# If we get to this exception, that is because the user has not taken the exam
			# But we still want to know how many other users have taken it
			e.exam_count = len(e.studenttakesexam_set.filter(exam=e).exclude(finished=None))
	return render(request, 'Exams/list.html', {'exam_list' : exam_list })


#AJAX FUNCTIONS
@csrf_exempt
def answer(request):
	if request.method == "POST":
		if request.is_ajax():
			option = Option.objects.get(id=request.POST['option_id'])
			mtm = StudentTakesExam.objects.get(id=request.POST['student_takes'])
			question = Question.objects.get(id=request.POST['question_id'])
			#if the student is changing his answer
			try:
				answer = StudentAnswersQuestion.objects.get(takes_exam=mtm, question=question)
				answer.option = option
				print answer.id
				answer.save()
				print answer.id
			#If student is answering for the first time	
			except:
				answer = StudentAnswersQuestion(takes_exam=mtm, question=question, option=option)
				answer.save()
			re = {'id' : '1'}
			return HttpResponse(json.dumps(re), status=200, mimetype='application/json')


@csrf_exempt
def edit_exam_data(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				e = Exam.objects.get(id=request.POST['exam_id'])
				e.name = request.POST['name']
				e.creation_date = request.POST['creation_date']
				e.due_date_time = request.POST['due_date']
				e.video = request.POST['video_url']
				e.save()
				re = {'id' : '1' }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

@csrf_exempt
def add_question(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				q = Question()
				q.exam = Exam.objects.get(id=request.POST['exam_id'])
				q.save()
				res = { 'id' : q.id }
				return HttpResponse(json.dumps(res), mimetype="application/json")
			except Exception, e:
				print e
				return HttpResponse(status=500)
	else:
		raise Http404

@csrf_exempt
def edit_question(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				q = Question.objects.get(id=request.POST['question_id'])
				q.question = request.POST['question']
				q.save()
				re = {'id' : q.id }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

@csrf_exempt
def delete_question(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				q = Question.objects.get(id=request.POST['question_id'])
				q.delete()
				re = {'id' : q.id }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

@csrf_exempt
def add_option(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				o = Option()
				o.question = Question.objects.get(id=request.POST['question_id'])
				o.save()
				res = { 'id' : o.id }
				return HttpResponse(json.dumps(res), mimetype="application/json")
			except Exception, e:
				print e
				return HttpResponse(status=500)
	else:
		raise Http404

@csrf_exempt
def edit_option(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				o = Option.objects.get(id=request.POST['option_id'])
				o.option = request.POST['option']
				o.save()
				re = {'id' : o.id }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

@csrf_exempt
def delete_option(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				o = Option.objects.get(id=request.POST['option_id'])
				o.delete()
				re = {'id' : o.id }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

@csrf_exempt
def edit_checkbox(request):
	if request.method == "POST":
		if request.is_ajax():
			try:
				o = Option.objects.get(id=request.POST['option_id'])
				if str(request.POST['correct']) == "True":
					o.correct = False
				else:
					o.correct= True
				#Get the old correct option before we save the new one.
				try:
					old_o = Option.objects.get(question=o.question, correct=True)
					print old_o
					old_o.correct = False
					old_o.save()
				except:
					pass
				o.save()
				if old_o:
					re = {'id' : old_o.id }
				else:
					re = {'id' : -1 }
				return HttpResponse(json.dumps(re), status=200, mimetype='application/json')
			except Exception, ex:
				print ex
				return HttpResponse(status=500)

NantiSchool/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from UsersExtended.models import UserProfile

@login_required
def home(request):
	return redirect('list_exams')

NantiSchool/templates/Exams/create.html
{% extends 'NantiSchool/home.html' %}

{% block list_exams %}active{% endblock %}

{% block style %}
	.hugeInput {font-size: 30px !important; height: 45px !important; width: 60% !important; }
	.hugeDate {font-size: 30px !important; height: 45px !important; width: 25% !important; }
	.hugeLabel {font-size: 25px; width: 20%; margin-top: 12px; }
	.questionInput {font-size: 30px !important; height: 45px !important; width: 90% !important;}
	#upperButtons {margin-bottom: 30px;}
	.deleteButton {color: red; height: 20px; width: 30px; font-size: 40px; opacity: 1;}
	.deleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
	.optionBox {width: 70%; background-image: url('/static/img/pw_maze_white.png'); height: 40px;}
	.OptiondeleteButton {color: red; height: 20px; width: 15px; font-size: 25px; opacity: 1; margin: -10px -10px 0 0;}
	.OptiondeleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
{% endblock %}

{% block content %}

<style>

	.hugeInput {font-size: 30px !important; height: 45px !important; width: 60% !important; }
	.hugeDate {font-size: 30px !important; height: 45px !important; width: 25% !important; }
	.hugeLabel {font-size: 25px; width: 20%; margin-top: 12px; }
	.questionInput {font-size: 30px !important; height: 45px !important; width: 90% !important;}
	#upperButtons {margin-bottom: 30px;}
	.deleteButton {color: red; height: 20px; width: 30px; font-size: 40px; opacity: 1;}
	.deleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
	.optionBox {width: 70%; background-image: url('/static/img/pw_maze_white.png'); height: 40px;}
	.OptiondeleteButton {color: red; height: 20px; width: 15px; font-size: 25px; opacity: 1; margin: -10px -10px 0 0;}
	.OptiondeleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
</style>

<div class="row">
	<a class="btn btn-large pull-right" href="{% url list_exams %}">Hætta</a>
		<form class="form-horizontal" >{% csrf_token %}
			<input type="hidden" id="examId" value="{{exam.id}}" />
			<div class="modal-header">
				<h1>Bæta við prófi</h1>
				<h5>Öllum spurningum og svarmöguleikum er bætt við prófið jafnóðum.</h5>
			</div>
			<div class="modal-body">
				<div class="control-group ">
					<label class="control-label hugeLabel" for="examName">Nafn prófs</label>
					<div class="controls">
						<input class="hugeInput" type="text" id="examName" name="name" placeholder="Ónefnt próf" style="line-height: 40px;" />
						<img id="nameLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label hugeLabel" for="examCreationDate">Upphafsdagur</label>
					<div class="controls">
						<input class="hugeDate" type="date" id="examCreationDate" name="creation_date" value="{{ exam.creation_date }}" /><img id="creationLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label hugeLabel" for="examDueDate">Skiladagur</label>
					<div class="controls"> 
						<input class="hugeDate" type="date" id="examDueDate" name="due_date_time" value="{{ exam.due_date_time }}" /><img id="dueLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
                <div class="control-group ">
                    <label class="control-label hugeLabel" for="examVideo">Myndband</label>
                    <div class="controls">
                        <input class="hugeInput" type="text" id="examVideo" name="name" placeholder="Slóð á myndband á MP4 formi" style="line-height: 40px;" />
                        <img id="videoLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
                    </div>
                </div>
			</div>
		</form>
		<div id="upperButtons">
			<button class="btn btn-success addQuestion" value="1">Bæta við spurningu</button>
		</div>
			<div id="questionList" >
				<hr/>
				{% if questions %}
					{% for q in questions %}
					<div id="Question-{{q.id}}" class="well"><button  class="close deleteButton" value="{{q.id}}" >&times;</button>
						<div class="control-group">
							<input class="questionInput" id="{{q.id}}" type="text" value="{{q.question}}" />
							<img id="Loader{{q.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
						</div>
						<div id="OptionList-{{q.id}}">
							{% for o in q.option_set.all %}
									<div id="Option-{{o.id}}" class="well optionBox"><button class="close OptiondeleteButton" value="{{o.id}}">&times;</button>
										<div class="control-group">
											<input class="OptionInput" id="{{o.id}}" name="option-{{o.id}}" type="text" value="{{o.option}}" />
											<img id="optionLoader-{{o.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
											<span style="margin: 0 10px 0 20px;">Rétt svar?</span>
											<input style="padding-left: 20px;" type="checkbox" id="{{o.id}}" value="{{o.correct}}"
											{% if o.correct == 1 %}checked="True"{% endif %} />
											<img id="CheckLoader-{{o.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
										</div>
									</div>
							{% endfor %}
						</div>
						<button  class="btn btn-primary" value="{{q.id}}">Bæta við svarmöguleika</button>
					</div>
					{% endfor %}
				{% else %}
				<div id="noQuestions">
					<h1>Það eru engar spurningar á þessu prófi.<h1/>
				</div>
				{% endif %}
			</div>
		<div id="lowerButtons">
			<button class="btn btn-success addQuestion" value="2">Bæta við spurningu</button>
		</div>
		<a class="btn btn-large pull-right" href="{% url list_exams %}">Hætta</a>
</div>

<script id="QuestionTmpl" type="text/x-jquery-tmpl">
	<div id="Question-${id}" class="well"><button class="close deleteButton" value="${id}">&times;</button>
		<div class="control-group">
			<input class="questionInput" id="${id}" type="text" placeholder="Sláðu inn spurninguna þína hér .." style="line-height: 40px;" />
			<img id="Loader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
		</div>
		<div id="OptionList-${id}"></div>
		<button  class="btn btn-primary" value="${id}">Bæta við svarmöguleika</button>
	</div>
</script>

<script id="OptionTmpl" type="text/x-jquery-tmpl">
	<div id="Option-${id}" class="well optionBox"><button class="close OptiondeleteButton" value="${id}">&times;</button>
		<div class="control-group">
			<input class="OptionInput" id="${id}" type="text" name="option-${id}" placeholder="Sláðu inn svarmöguleikann hér.."/>
			<img id="Loader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
			<span style="margin: 0 10px 0 20px;">Rétt svar?</span>
			<input type="checkbox" id="${id}" value="0" />
			<img id="CheckLoader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
		</div>
	</div>
</script>



{% endblock %}

NantiSchool/templates/Exams/edit.html
{% extends 'NantiSchool/home.html' %}

{% block create_exam %}active{% endblock %}

{% block style %}
	.hugeInput {font-size: 30px !important; height: 45px !important; width: 60% !important; }
	.hugeDate {font-size: 30px !important; height: 45px !important; width: 25% !important; }
	.hugeLabel {font-size: 25px; width: 20%; margin-top: 12px; }
	.questionInput {font-size: 30px !important; height: 45px !important; width: 90% !important;}
	#upperButtons {margin-bottom: 30px;}
	.deleteButton {color: red; height: 20px; width: 30px; font-size: 40px; opacity: 1;}
	.deleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
	.optionBox {width: 70%; background-image: url('/static/img/pw_maze_white.png'); height: 40px;}
	.OptiondeleteButton {color: red; height: 20px; width: 15px; font-size: 25px; opacity: 1; margin: -10px -10px 0 0;}
	.OptiondeleteButton:hover {text-decoration: none; color: red; opacity: 0.8;}
{% endblock %}

{% block content %}



<div class="row">
	<a class="btn btn-large pull-right" href="{% url list_exams %}">Hætta</a>
		<form class="form-horizontal" >{% csrf_token %}
			<input type="hidden" id="examId" value="{{exam.id}}" />
			<div class="modal-header">
				<h1>Breyta prófi</h1>
				<h5>Prófinu og svarmöguleikum er breytt jafnóðum.</h5>
			</div>
			<div class="modal-body">
				<div class="control-group ">
					<label class="control-label hugeLabel" for="examName">Nafn prófs</label>
					<div class="controls">
						<input class="hugeInput" type="text" id="examName" name="name" value="{{ exam.name }}" />
						<img id="nameLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label hugeLabel" for="examCreationDate">Upphafsdagur</label>
					<div class="controls">
						<input class="hugeDate" type="date" id="examCreationDate" name="creation_date" value="{{ exam.creation_date }}" /><img id="creationLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label hugeLabel" for="examDueDate">Skiladagur</label>
					<div class="controls"> 
						<input class="hugeDate" type="date" id="examDueDate" name="due_date_time" value="{{ exam.due_date_time }}" /><img id="dueLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
					</div>
				</div>
                <div class="control-group ">
                    <label class="control-label hugeLabel" for="examVideo">Myndband</label>
                    <div class="controls">
                        <input class="hugeInput" type="text" id="examVideo" name="name" {% if exam.video %} value="{{ exam.video }}" {% else %} placeholder="Slóð á myndband á MP4 formi"{% endif %} style="line-height: 40px;" />
                        <img id="videoLoader" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
                    </div>
                </div>
			</div>
		</form>
		<div id="upperButtons">
			<button class="btn btn-success addQuestion" value="1">Bæta við spurningu</button>
		</div>
			<div id="questionList" >
				<hr/>
				{% if questions %}
					{% for q in questions %}
					<div id="Question-{{q.id}}" class="well"><button  class="close deleteButton" value="{{q.id}}" >&times;</button>
						<div class="control-group">
							<input class="questionInput" id="{{q.id}}" type="text" value="{{q.question}}" />
							<img id="Loader{{q.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
						</div>
						<div id="OptionList-{{q.id}}">
							{% for o in q.option_set.all %}
									<div id="Option-{{o.id}}" class="well optionBox"><button class="close OptiondeleteButton" value="{{o.id}}">&times;</button>
										<div class="control-group">
											<input class="OptionInput" id="{{o.id}}" name="option-{{o.id}}" type="text" value="{{o.option}}" />
											<img id="optionLoader-{{o.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
											<span style="margin: 0 10px 0 20px;">Rétt svar?</span>
											<input style="padding-left: 20px;" type="checkbox" id="{{o.id}}" value="{{o.correct}}"
											{% if o.correct == 1 %}checked="True"{% endif %} />
											<img id="CheckLoader-{{o.id}}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
										</div>
									</div>
							{% endfor %}
						</div>
						<button  class="btn btn-primary" value="{{q.id}}">Bæta við svarmöguleika</button>
					</div>
					{% endfor %}
				{% else %}
				<div id="noQuestions">
					<h1>Það eru engar spurningar í þessu prófi.<h1/>
				</div>
				{% endif %}
			</div>
		<div id="lowerButtons">
			<button class="btn btn-success addQuestion" value="2">Bæta við spurningu</button>
		</div>
	<a class="btn btn-large pull-right" href="{% url list_exams %}">Hætta</a>
</div>

<script id="QuestionTmpl" type="text/x-jquery-tmpl">
	<div id="Question-${id}" class="well"><button class="close deleteButton" value="${id}">&times;</button>
		<div class="control-group">
			<input class="questionInput" id="${id}" type="text" placeholder="Sláðu inn spurninguna þína hér .." style="line-height: 40px;" />
			<img id="Loader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
		</div>
		<div id="OptionList-${id}"></div>
		<button  class="btn btn-primary" value="${id}">Bæta við svarmöguleika</button>
	</div>
</script>

<script id="OptionTmpl" type="text/x-jquery-tmpl">
	<div id="Option-${id}" class="well optionBox"><button class="close OptiondeleteButton" value="${id}">&times;</button>
		<div class="control-group">
			<input class="OptionInput" id="${id}" type="text" name="option-${id}" placeholder="Sláðu inn svarmöguleikann hér.."  />
			<img id="Loader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
			<span style="margin: 0 10px 0 20px;">Rétt svar?</span>
			<input type="checkbox" id="${id}" value="0" />
			<img id="CheckLoader${id}" style="margin-left: 15px; display: none;" height="23px" width="23px" src="/static/img/loader.gif" />
		</div>
	</div>
</script>



{% endblock %}